### ISSUE TITLE
Provide Summary block of what cargo-pants finds

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/cargo-pants#14]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Provide a summary of what was scanned and what was found:

<img width="377" alt="Screen Shot 2020-08-14 at 10 21 20 AM" src="https://user-images.githubusercontent.com/5544326/90280723-e7099380-de17-11ea-8c96-0a8ddfcef956.png">
^^^ from Nancy, likely crafting something similar would be ideal

* **What feature or behavior is this required for?**

It just gives some quick information to someone consuming the output of `cargo-pants` and let's them know if they should visually scan

* **How could we solve this issue? (Not knowing is okay!)**

No clue, good luck!

* **Anything else?**

Have fun!

**Comment by Kapple14** [comment]
Hey! 👋 

Super cool 🦀 project. I highly appreciate your work and hope you are still involved with the project? I have created some pull request for this repo here: [https://github.com/sonatype-nexus-community/cargo-pants/pull/72](https://github.com/sonatype-nexus-community/cargo-pants/pull/72)

Happy to code more
