### ISSUE TITLE
Pretty up the output of a found vulnerability

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/cargo-pants#15]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

For a found vulnerability on a library, we probably want to output it in a much easier to read way

<img width="1020" alt="Screen Shot 2020-08-14 at 10 23 55 AM" src="https://user-images.githubusercontent.com/5544326/90280955-436cb300-de18-11ea-84bd-206d118107ca.png">
^^^ From Nancy, if multiple vulns are found, we'd output it in recurring tables and adjust the number found

The title of the vuln can be switched to be a color that reflects the severity of the vulnerability, as well as the title of the package. Some code from Nancy can help inform this: https://github.com/sonatype-nexus-community/nancy/blob/master/audit/auditlogtextformatter.go#L116-L141

* **What feature or behavior is this required for?**

Just makes it easier to read what is going on and easier to visually scan.

* **How could we solve this issue? (Not knowing is okay!)**

Not sure. Have fun!

* **Anything else?**

Probably want to use a library that disables color on terminals that do not support it, or via a flag such as `--no-color` for people who might be color blind!

**Comment by MichelKazi** [comment]
This might be a start https://github.com/phsym/prettytable-rs

**Comment by bhamail** [comment]
Fixed in #25
