### ISSUE TITLE
Running 'cargo pants' fails with 'Unexpected argument parts'

### ISSUE THREAD

**Issue by mobiuscog** [sonatype-nexus-community/cargo-pants#5]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Run **cargo pants** (version 0.0.5)

It responds with:
>$ cargo pants
>Usage:
>    /Users/michael/.cargo/bin/cargo-pants [OPTIONS]
>/Users/michael/.cargo/bin/cargo-pants: Unexpected argument pants

* **What feature or behavior is this required for?**
Basic functionality

* **How could we solve this issue? (Not knowing is okay!)**
It looks as if something is wrong with the argument parsing

* **Anything else?**
Version 0.0.4 seems to work fine, so it is a change in the latest code.
Running **cargo-pants** works fine.

**Comment by gmohre** [comment]
This should be fixed with the latest commit https://github.com/sonatype-nexus-community/cargo-pants/commit/fcbc993b4f258f930df204b8da84457e81e8e801 Thanks for the issue.

**Comment by mobiuscog** [comment]
That works great. Thanks for the quick fix 👍
