### ISSUE TITLE
Vunerability title displays in an HTML encoded form

### ISSUE THREAD

**Issue by amy-keibler** [sonatype-nexus-community/cargo-pants#54]
A vulnerability's `title` appears to be HTML encoded.

### Reproduction Steps

1. Install the latest `cargo-pants` (`cargo install cargo-pants`)
2. Clone the git repository for this project (`git clone git@github.com:sonatype-nexus-community/cargo-pants.git && cd cargo-pants/`
3. Check out the version mentioned in issue #53 (`git checkout 0.1.26`)
4. Run `cargo-pants` on the repository (`cargo pants`)
5. Observe the vulnerability title for `lock_api` displayed as `lock&#95;api`

### Questions

* Are any other fields HTML encoded? From my initial inspection, `title` appears to be the only one

**Comment by bhamail** [comment]
I started digging into this, and I'm pretty sure the issue is fixed (couldn't reproduce the html encoded title). Please holler if this is still an issue.

While digging, I did find another boog: https://github.com/sonatype-nexus-community/cargo-pants/issues/69

**Comment by bhamail** [comment]
I believe this was fixe by prior commits. Please reopen if needed.
